feat(lazygit): add custom command to create PR and merge it

diff --git a/.config/lazygit/config.yml b/.config/lazygit/config.yml
--- a/.config/lazygit/config.yml
+++ b/.config/lazygit/config.yml
@@ -56,8 +56,7 @@ customCommands:
     description: Custom commands
     commandMenu:
       - key: c
-        command:
-          'echo "$(git rev-parse --show-toplevel) {{.SelectedCommitRange.From}} {{.SelectedCommitRange.To}}" | pbcopy'
+        command: 'echo "$(git rev-parse --show-toplevel) {{.SelectedCommitRange.From}} {{.SelectedCommitRange.To}}" | pbcopy'
         context: commits, subCommits
         description: "Copy selected commits to clipboard (paste in another local repo)"
       - key: v
@@ -107,6 +106,40 @@ customCommands:
         command:
           git -c core.attributesFile=/dev/null rebase --autostash --keep-empty --no-autosquash --rebase-merges
           "{{.SelectedLocalBranch.Name}}"
+      - key: p
+        description: Create PR
+        context: localBranches
+        prompts:
+          - type: menu
+            title: Select the merge strategy
+            key: MergeStrategy
+            options:
+              - name: Squash
+                value: "gh pr merge '{{.SelectedLocalBranch.Name}}' --auto --squash --delete-branch"
+              - name: Rebase
+                value: "gh pr merge '{{.SelectedLocalBranch.Name}}' --auto --rebase --delete-branch"
+
+        command: |
+          #!/bin/bash
+          set -euo pipefail
+
+          BRANCH="{{.SelectedLocalBranch.Name}}"
+          REMOTE_NAME="$(git config "branch.$BRANCH.remote" || true)"
+          if [[ -z "$REMOTE_NAME" ]]; then
+            echo "Branch $BRANCH does not track a remote, cannot create PR" >&2
+            exit 1
+          fi
+
+          REMOTE_URL="$(git remote get-url "$REMOTE_NAME")"
+          if [[ "$REMOTE_URL" == *"github"* || "$REMOTE_URL" == *"ghe.com"* ]]; then
+            PR=$(gh pr create --fill --base main --head "$BRANCH" --assignee "@me")
+            echo "Created PR: $PR"
+            open "$PR" # open it in the browser
+            {{.Form.MergeStrategy}}
+          else
+            echo "Unsupported forge for PR creation: $REMOTE_URL" >&2
+            exit 1
+          fi
   - key: "="
     description: "Update MR/PR description"
     context: localBranches
